Hare ears
SPLURT-Station/S.P.L.U.R.T-Station-13 pull request #1169
Opened 2024-06-14 16:04 UTC by miguelop1

Hare ears

# About The Pull Request
We add Hare ears. Created by o0xroxasx0o2600

## Why It's Good For The Game
More ears moment

## A Port?
no

## Pre-Merge Checklist

- [ ] You tested this on a local server.
- [ ] This code did not runtime during testing.
- [ ] You documented all of your changes.

## Changelog

:cl:
add: Added more ears
:cl:

2024-06-14 16:04 UTC, miguelop1 commented
Aint working yet.

2024-06-17 01:27 UTC, Kilmented commented
> ain't working yet
famous last words

2024-06-17 01:34 UTC, Tk420634 commented
> Aint working yet.

caught in 4k

2024-06-20 07:32 UTC, BongaTheProto requested changes

2024-06-20 07:32 UTC, BongaTheProto commented on code/modules/mob/dead/new_player/sprite_accessories/ears.dm
> +	color_src = MATRIXED
```suggestion
    icon_state = "hare"
    color_src = MATRIXED
```

2024-06-20 07:32 UTC, BongaTheProto commented on code/modules/mob/dead/new_player/sprite_accessories/ears.dm
> +	color_src = MATRIXED
```suggestion
    icon_state = "hare"
    color_src = MATRIXED
```

2024-06-20 23:38 UTC, miguelop1 commented on code/modules/mob/dead/new_player/sprite_accessories/ears.dm
> +	color_src = MATRIXED
Alright the stupid shit fixed

2024-06-21 19:42 UTC, BongaTheProto commented
Please modularize your code into modular_splurt

2024-07-27 21:00 UTC, merged