4ward Nanotrasen Acquired Location Station
SPLURT-Station/S.P.L.U.R.T-Station-13 pull request #1188
Opened 2024-08-08 21:18 UTC by SaraSayomi

# About The Pull Request
This is a fully new station, initially started after a snaxi round and being annoyed at our current multi-z stations and draws inspiration from all existing stations including northstar as I tried to make a large map that felt cozy. It comes complete with custom arrival, emergency, and whiteship shuttles to really give it personal flair. Consisting of a round main level with all departments represented for ease of navigation this level serves as a primary hub for all sections of the station, no more wandering around Layena's 2nd port starboard wing only to learn you are in the wrong half of the staion and need to find 5 minutes locating stairs. Going down we reach the maints warren, intended to house the the prisons in a fairly isolated branch, as well as the normal isolation the chapel has. Going up to the top leads to the professional's floor, the majority of it housing R&D, Engi, Command, and Medical's lounge. If any questions about the layout, design choices, or even lore are had feel free to message my discord or in the thread I'm making in the mapping subsection. I have already talked with our resident mad Engi Sato about some of my SM choices.

I have refrained from adding it into my config files, so I do not mess with the server's local ones, it will have to be manually added.

I will continue to support this map, bug fix, and update it after the rebase.

#bottom layer
<a href="https://gyazo.com/4cb5c81312103d83126a70ab11d9d644"><img src="https://i.gyazo.com/4cb5c81312103d83126a70ab11d9d644.png" alt="Bottom layer" width="8160"/></a>

#Primary layer
<a href="https://gyazo.com/f45010475888103a260ceeb630041066"><img src="https://i.gyazo.com/f45010475888103a260ceeb630041066.png" alt="Image from Gyazo" width="8160"/></a>

#Professional's layer
<a href="https://gyazo.com/b3b2e9d0422d427aedfda57df9919d98"><img src="https://i.gyazo.com/b3b2e9d0422d427aedfda57df9919d98.png" alt="Image from Gyazo" width="8160"/></a>

#Arrival shuttle
<a href="https://gyazo.com/ad35a13fc06a18fb639475ca40a4c026"><img src="https://i.gyazo.com/ad35a13fc06a18fb639475ca40a4c026.png" alt="Image from Gyazo" width="288"/></a>

#Whiteship
<a href="https://gyazo.com/7d8185a350603c2e0cec9b57715c4375"><img src="https://i.gyazo.com/7d8185a350603c2e0cec9b57715c4375.png" alt="Image from Gyazo" width="896"/></a>

#Escape shuttle
<a href="https://gyazo.com/09ee41c5d461503c3361de905a8c56c9"><img src="https://i.gyazo.com/09ee41c5d461503c3361de905a8c56c9.png" alt="Image from Gyazo" width="672"/></a>

## Why It's Good For The Game
It's a new station, this one is built for splurt's style of play, and variety is after all, the spice of life.

## A Port?
Not a port, this is a original station, some parts look very similar to others due to me making sure I had room requirements by comparing as I built, including to northstar and donut.

## Pre-Merge Checklist

- [x] You tested this on a local server.
- [x] This code did not runtime during testing. (only decals that are not coded 100%, cum drips primarily)
- [x] You documented all of your changes.

## Changelog

:cl:Sara
add: Added a full new station.
add: Added new shuttles, arrival, escape, and whiteship.
add: Added new lore page for the station.
/:cl:

2024-08-09 21:04 UTC, MosleyTheMalO requested changes

2024-08-09 21:04 UTC, MosleyTheMalO commented on _maps/splurt_maps/map_files/4Nalstation/4NaL Station.dmm
Please save this file again in sdmm but make sure you enable the TGM formatting

also, install the git hooks in tools/hooks/install.bat

2024-08-09 21:16 UTC, SaraSayomi commented on _maps/splurt_maps/map_files/4Nalstation/4NaL Station.dmm
Doing so now, and fighting the hooks because they either don't install right or think I have python 3.7

2024-08-12 00:57 UTC, SaraSayomi commented
Well I expected the wide test would find bugs, and I was correct, fix is made just needs to be pushed live

2024-10-24 08:44 UTC, merged