Ghost ass slapping has arrived
SPLURT-Station/S.P.L.U.R.T-Station-13 pull request #314
Opened 2022-05-04 10:54 UTC by PurpleFenn

# About The Pull Request
With the GHOST_INTERACTION config flag, ghosts can now slap the ass of players who have the ass slap pref enabled! Neat!

## Why It's Good For The Game
Why not? It's able to be disabled pretty easily via a config flag.

## A Port?
Not at all

## Pre-Merge Checklist

- [ ] You tested this on a local server.
- [ ] This code did not runtime during testing.
- [ ] You documented all of your changes.

## Changelog

:cl:
add: The ability to slap the ass of physical beings as a ghost. Spooky ☠☠
/:cl:

2022-05-04 10:55 UTC, PurpleFenn commented
Leaving runtime unticked because it's not fully tested. Ass slapping works fine but there might still be cases in which runtimes occur since I specifically used the syntax that allows runtimes to happen instead of compilation error to avoid having to deal with some bs later

2022-05-06 04:08 UTC, BongaTheProto requested changes

2022-05-06 04:08 UTC, BongaTheProto commented on modular_splurt/code/_onclick/observer.dm
> +		src:mob_climax(forced_climax=TRUE, cause="masochism")
```suggestion
	if(istype(H))
		H.adjust_arousal(20, "masochism", maso=TRUE)
		if(HAS_TRAIT(H, TRAIT_MASO) && H.has_dna() && prob(10))
			H.mob_climax(forced_climax=TRUE, cause="masochism")
```

2022-05-06 04:08 UTC, BongaTheProto commented on modular_splurt/code/_onclick/observer.dm
> +		src:mob_climax(forced_climax=TRUE, cause="masochism")
```suggestion
	if(istype(H))
		H.adjust_arousal(20, "masochism", maso=TRUE)
		if(HAS_TRAIT(H, TRAIT_MASO) && H.has_dna() && prob(10))
			H.mob_climax(forced_climax=TRUE, cause="masochism")
```

2022-05-06 04:08 UTC, BongaTheProto commented on modular_splurt/code/_onclick/observer.dm
> +	var/mob/living/carbon/H = src
```suggestion
	var/mob/living/carbon/human/H = src
```

2022-05-06 04:08 UTC, BongaTheProto commented on modular_splurt/code/_onclick/observer.dm
> +	var/mob/living/carbon/H = src
```suggestion
	var/mob/living/carbon/human/H = src
```

2022-05-06 04:12 UTC, BongaTheProto commented
I think this will probably be better

2022-05-07 04:32 UTC, BongaTheProto approved these changes

2022-05-08 20:05 UTC, merged