Add a limited time Halloween alt-title to security
SPLURT-Station/S.P.L.U.R.T-Station-13 pull request #529
Opened 2022-10-08 16:36 UTC by LonoferaRS

Suggestion by Bob Danger
Add a limited time Halloween alt-title to security called: 'Spookcurity'. Such as 'Head of Spook[curity]', 'Spook[curity] officer', etc.

2022-10-08 16:39 UTC, BongaTheProto commented
Please fill the PR form properly

2022-10-08 17:00 UTC, LonoferaRS commented
fixed*

2022-10-08 18:29 UTC, BongaTheProto requested changes

2022-10-08 18:29 UTC, BongaTheProto commented on modular_splurt/code/modules/jobs/job_types/_job_alt_titles.dm
> +		"Head of Spookcurity"
```suggestion
		"Head of Slutcurity"
	)
	if(SSevents.holidays && SSevents.holidays[HALLOWEEN])
		LAZYADD(extra_titles, "Head of Spookcurity")
```
You'll wanna do something like this for each one of the extra titles so they're actually halloween limited

2022-10-09 22:12 UTC, BongaTheProto approved these changes

2022-10-09 22:12 UTC, merged