vampire coffin update
SPLURT-Station/S.P.L.U.R.T-Station-13 pull request #560
Opened 2022-10-19 03:04 UTC by Nukechickenu64

# About The Pull Request
makes the coffin heal toxin and burn, toxin being alot because toxin is a serious issue when the vampires go crit cause they get a steady amount of damage, this is compatible with slime species, burn only a little

## Why It's Good For The Game
makes it possible to revive vampires

## A Port?
no

## Pre-Merge Checklist

- [ ] You tested this on a local server.
- [ ] This code did not runtime during testing.
- [ ] You documented all of your changes.

## Changelog

:cl:
fix: made the vampire heal ALOT of toxin in coffins so its alot easier to revive them after being crit for a long time
/:cl:

2022-10-20 02:11 UTC, JerryWester commented
Out of curiosity:
> fix: made the vampire heal toxin in coffins
Does this account for slimes?

2022-10-20 02:14 UTC, JerryWester commented on modular_splurt/code/datums/traits/neutral.dm
> +			C.adjustToxLoss(5)//heals toxin if slime
Pfft, nevermind, retract my previous question

2022-10-21 21:25 UTC, Nukechickenu64 commented
> Out of curiosity:
> > fix: made the vampire heal toxin in coffins
> 
> Does this account for slimes?

Yes

2022-10-22 00:39 UTC, BongaTheProto requested changes

2022-10-22 00:39 UTC, BongaTheProto commented on modular_splurt/code/datums/traits/neutral.dm
> +	var/datum/action/vrevive/R = new
You need to add a removal for this in on_remove like for the vbite one

2022-10-28 22:00 UTC, BongaTheProto requested changes

2022-10-28 22:00 UTC, BongaTheProto commented on modular_splurt/code/datums/traits/neutral.dm
> +	var/datum/action/vbite/R = locate() in H.actions
```suggestion
	var/datum/action/vrevive/R = locate() in H.actions
```

2022-10-28 22:45 UTC, BongaTheProto requested changes

2022-10-28 22:45 UTC, BongaTheProto commented on modular_splurt/code/datums/traits/neutral.dm
> +	var/mob/living/carbon/human/H = quirk_holder
Just remove the C variable and use H for everything

2022-10-28 22:52 UTC, JerryWester commented on modular_splurt/code/datums/traits/neutral.dm
> +		if(rand(0,100) =< 10) //10 percent chance (if it was true randome D:<)
I think you can just do `rand(10)`

2022-10-28 22:53 UTC, BongaTheProto commented on modular_splurt/code/datums/traits/neutral.dm
> +		if(rand(0,100) =< 10) //10 percent chance (if it was true randome D:<)
> I think you can just do `rand(10)`

You mean `prob(10)`

2022-10-29 00:02 UTC, BongaTheProto requested changes

2022-10-29 00:02 UTC, BongaTheProto commented on modular_splurt/code/datums/traits/neutral.dm
> +species
```suggestion

```

2022-10-31 03:43 UTC, JerryWester commented
For being a neutral quirk, this is adding quite a bit of positive traits

2022-10-31 03:57 UTC, Nukechickenu64 commented
> For being a neutral quirk, this is adding quite a bit of positive traits

might add the ability to remove some of these traits by external forces, like a stake after death removes the ability to resurrect, and remember that ressurecting makes them extremely dizzy and have 0 nutrition which is even worst for them cause theyre stamina gets maxed at 1 when they have 0 nutrition

2022-11-02 02:45 UTC, merged