Removes headslugs from gold slime pool, adds venus man eaters.
SPLURT-Station/S.P.L.U.R.T-Station-13 pull request #577
Opened 2022-10-27 20:26 UTC by chefferz

Removes the ability to self-antag and make yourself ling from the gold slime pool.

Replaces removed headslug with venus man eater.

2022-10-28 22:14 UTC, Zirok-BYOND commented
Calling xenobio lings self-antag is simply incorrect, I don't believe xenobio lings have any special status on Splurt. They just get fancy powers and that's that!

2022-11-15 11:33 UTC, SpookyTheFox requested changes

2022-11-15 11:33 UTC, SpookyTheFox commented on code/modules/mob/living/simple_animal/hostile/venus_human_trap.dm
> +	gold_core_spawnable = HOSTILE_SPAWN
Adding this here makes a child class mob inherit it. In this case, `/mob/living/simple_animal/hostile/venus_human_trap/ghost_playable` thus adding venus man traps twice, not once. Consider if you want the click-to-play version or the normal one, and either move `gold_core_spawnable = HOSTILE_SPAWN` to the click-to-play, or add `gold_core_spawnable = NO_SPAWN` to the other one below.

2023-01-05 13:29 UTC, Mazen421 commented
Sorta lame not gonna lie

2023-03-07 05:33 UTC, closed without merging