Homgry
SPLURT-Station/S.P.L.U.R.T-Station-13 pull request #597
Opened 2022-11-15 00:49 UTC by JerryWester

# About The Pull Request

Doubles the rate of hunger and thirst in exchange for a trait point. Doesn't account for `NO_HUNGER` or `NO_THIRST`. Also doesn't account for synths. Done at the request of CinKro#1001, [Suggestion #3393](https://discord.com/channels/908082639704064051/1040135231786721330)

## Why It's Good For The Game

homger

## A Port?

No

## Pre-Merge Checklist

- [x] You tested this on a local server.
- [x] This code did not runtime during testing.
- [x] You documented all of your changes.

## Changelog

:cl:
add: Added the "Hungry and Thirsty" negative quirk, grants one point and doubles the hunger/thirst modifier
/:cl:

2022-11-17 19:48 UTC, CinKro commented
I love you I have wanted this for so long

2022-11-28 22:57 UTC, BongaTheProto commented on modular_splurt/code/modules/mob/living/carbon/human/species.dm
> +	if (H.thirst > 0 && H.stat != DEAD && !HAS_TRAIT(H, TRAIT_NOHUNGER))
shouldn't it be TRAIT_NOTHIRST?

2022-12-04 06:02 UTC, JerryWester commented on modular_splurt/code/modules/mob/living/carbon/human/species.dm
> +	if (H.thirst > 0 && H.stat != DEAD && !HAS_TRAIT(H, TRAIT_NOHUNGER))
Yes, I am the stupid

2022-12-08 16:25 UTC, BongaTheProto requested changes

2022-12-08 16:25 UTC, BongaTheProto commented on modular_splurt/code/modules/mob/living/carbon/human/species.dm
> +		H.adjust_nutrition(-thirst_rate)
```suggestion
		H.adjust_thirst(-thirst_rate)
```

2022-12-17 01:33 UTC, merged