Updating russian localization
SPLURT-Station/S.P.L.U.R.T-Station-13 pull request #606
Opened 2022-11-28 15:24 UTC by Kush1Push1

## About The Pull Request

Updated russian localization to certain radio channels and some other chat's functions.

## Why It's Good For The Game

Keeping the code up-to date and fixes a bug for newly created ru-servers (lack of ability to say in radio without using english keyboard).

[Also I already merged it in /tg/station.](https://github.com/tgstation/tgstation/pull/56882)

## Changelog
:cl: SishTis
fix: Updated russian keyboard localization. You can now use russian letter as prefix for radio channel, like, :у for engineering.
/:cl:

2022-11-28 21:28 UTC, BongaTheProto requested changes

2022-11-28 21:28 UTC, BongaTheProto commented on code/modules/mob/living/say.dm
> +	"щ" = RADIO_CHANNEL_AI_PRIVATE
```suggestion
	"щ" = RADIO_CHANNEL_AI_PRIVATE,
```

2022-11-29 07:21 UTC, Kush1Push1 commented
Oof. Fixed.

2022-11-30 16:25 UTC, BongaTheProto approved these changes

2022-11-30 16:25 UTC, merged