Allow empath to detect Distant and Headpat Slut
SPLURT-Station/S.P.L.U.R.T-Station-13 pull request #627
Opened 2022-12-10 15:46 UTC by LeDrascol

# About The Pull Request
Allows players with the Empath or Friendly quirk to detect when another player has the Distant or Headpat Slut quirks.

_Originally suggested by Average Water Enjoyer#5949
Modified to also allow detecting Headpat Slut_

## Why It's Good For The Game
Quoting the original request:
_"Friendly characters are more likely to use the 1 positive point they used that doesn't benefit them at all but benefit others to headpat and hug people. Funny mood boosts. This gives them a tell on who doesn't want to be headpatted."_
\- Average Water Enjoyer#5949

Not having a tell for who doesn't want to be touched causes awkward interactions, and sometimes (5% chance) triggers an attack action. Adding an additional tell for people who requested (via quirk) to be touched also made logical sense.

## A Port?
No.

## Pre-Merge Checklist
- [ ] You tested this on a local server.
- [ ] This code did not runtime during testing.
- [ ] You documented all of your changes.

## Changelog
:cl:
tweak: Empath and Friendly crew can now detect Distant and Headpat Slut crew
/:cl:

2022-12-10 16:07 UTC, BongaTheProto requested changes

2022-12-10 16:07 UTC, BongaTheProto commented on modular_splurt/code/modules/mob/mob_helpers.dm
> +	// Please change this when adding new quirk detection
```suggestion
	. = ..()
	// Empathy abilities escape clause
	// Please change this when adding new quirk detection
```

2022-12-10 17:37 UTC, BongaTheProto commented on modular_splurt/code/modules/mob/mob_helpers.dm
> +		. += "<span class='info'>You sense [t_He] appreciates reviving physical affection more than normal.</span>\n"
I feel like you meant receiving

2022-12-11 04:24 UTC, LeDrascol commented on modular_splurt/code/modules/mob/mob_helpers.dm
> +		. += "<span class='info'>You sense [t_He] appreciates reviving physical affection more than normal.</span>\n"
You're right! That was a silly typo.

2022-12-13 18:43 UTC, merged