Automatic SSD cryo
SPLURT-Station/S.P.L.U.R.T-Station-13 pull request #646
Opened 2022-12-21 21:37 UTC by LeDrascol

# About The Pull Request
Adds a new subsystem that checks when a logged-out player has been SSD for a minimum of 40 minutes, then sends them to cryo.

## Why It's Good For The Game
- Prevents SSD players from holding job slots forever
- Prevents unreachable or hidden SSD players being stuck forever
- Removes the need to manually cryo crewmates
- Resolves Suggestion #3498 by Rysiek#6230

## A Port?
Originally based on https://github.com/ParadiseSS13/Paradise/pull/11732, but simplified to the minimum required elements.

## Pre-Merge Checklist
- [X] You tested this on a local server.
- [X] This code did not runtime during testing.
- [X] You documented all of your changes.

## Changelog

:cl:
tweak: SSD players are automatically sent to cryo after 40 minutes
/:cl:

2022-12-22 02:12 UTC, BongaTheProto commented
It would be good to make the amount of minutes before auto cryoing a config rather than a define

2022-12-22 02:20 UTC, LeDrascol commented
> It would be good to make the amount of minutes before auto cryoing a config rather than a define

That's definitely a better idea. I had difficulties figuring out config code, and decided to prioritize making the system work at a basic level first.

2022-12-22 18:26 UTC, BongaTheProto commented
> That's definitely a better idea. I had difficulties figuring out config code, and decided to prioritize making the system work at a basic level first.

It's not that hard, you can declare a config like the other ones in the modular code

2022-12-24 18:02 UTC, BongaTheProto requested changes

2022-12-24 18:02 UTC, BongaTheProto commented on config/splurt/autocryo.txt
> +# AUTOCRYO_DISABLED
Would be better if instead of a flag to disable it there was a flag to _enable_ it and that it came disabled by default

2023-01-01 16:37 UTC, BongaTheProto commented
It seem that it's crying people when they go into vr. And it does so with their VR items too, meaning people can go to the oversight panel and take the items they had when they were in VR

2023-02-14 23:37 UTC, merged