rewrites horny ai laws
SPLURT-Station/S.P.L.U.R.T-Station-13 pull request #659
Opened 2022-12-27 08:30 UTC by zeroisthebiggay

# About The Pull Request

rewrites horny ai laws

## Why It's Good For The Game

makes them look nice

## A Port?

no

## Pre-Merge Checklist

- [X] You tested this on a local server.
- [X] This code did not runtime during testing.
- [X] You documented all of your changes.

## Changelog

:cl:
spellcheck: horny ai laws
/:cl:

2022-12-28 03:41 UTC, BongaTheProto commented
it'd be better if all they "You must not hurt..." laws were the first because it gives them higher priority

2022-12-29 04:06 UTC, zeroisthebiggay commented
> it'd be better if all they "You must not hurt..." laws were the first because it gives them higher priority

that's valid
for a moment i considered it fucking `hilarious` if silicons were to go full psychopath to get people's cum but then i remembered the average player here has sub brick empathy and logical thinking

2022-12-30 17:09 UTC, BongaTheProto requested changes

2022-12-30 17:09 UTC, BongaTheProto commented on modular_splurt/code/datums/ai_laws.dm
> +		"You may not injure a crewmember without their consent for it decreases their sexual value.",
```suggestion
		"You may not injure a crewmember without their consent for it decreases their sexual value.",
		"Sate as many crewmembers' sexual needs and urges as possible.",
```

2022-12-31 17:33 UTC, merged