Adds Some Croptops
SPLURT-Station/S.P.L.U.R.T-Station-13 pull request #731
Opened 2023-02-02 04:25 UTC by Zattarra

# About The Pull Request

Adds three croptops of varying sleeve lengths. Also adds them to the loadout and clothesmate.

## Why It's Good For The Game

Saw some people asking for this and it seemed simple enough.

## A Port?

Not a port.

## Pre-Merge Checklist

- [ ] You tested this on a local server.
- [ ] This code did not runtime during testing.
- [ ] You documented all of your changes.

## Changelog

:cl:
add: Added the shortcrop, longcrop, and formalcrop.
add: Added croptops to loadout.
add: Added croptops to clothesmate.
imageadd: Gave the croptops sprites.
/:cl:

2023-02-02 06:13 UTC, BongaTheProto commented
can you plz modularize these changes?

2023-02-02 06:15 UTC, Zattarra commented
AH SHIT.

2023-02-02 21:14 UTC, BongaTheProto commented
the rest of the code and icons can still be modularized

2023-02-03 03:11 UTC, Zattarra commented
Yes, I know.

2023-02-03 04:24 UTC, Zattarra commented
OH SHIT, THAT'S NOT HOW I DO IT.

2023-02-03 04:46 UTC, Zattarra commented
I think that broke more stuff.

2023-02-03 06:09 UTC, Zattarra commented
I am absolutely not sure what's up, searched it up on the discord, and maybe there's something with unticking files. No idea what that means.

2023-02-03 07:26 UTC, Zattarra commented
Imma try un-modularizing that bit and seeing if it works again.

2023-02-03 09:16 UTC, Zattarra commented
I think I made it work with modularization.

2023-02-07 03:16 UTC, BongaTheProto commented
seems they don't properly add to the backpack when joining

2023-02-07 04:36 UTC, Zattarra commented
Hmm, that is quite strange. I got them to appear in my backpack when added via loadout on my test server.

2023-02-07 20:50 UTC, BongaTheProto commented
> Hmm, that is quite strange. I got them to appear in my backpack when added via loadout on my test server.
> 
> It also appears to work when coming in late via shuttle.

Doesn't seem to be the case here
![ezgif-4-11d76c8434](https://user-images.githubusercontent.com/93835010/217362468-0c1b0588-049a-4eb3-9285-09b1732ddddc.gif)

2023-02-08 01:31 UTC, Zattarra commented
I will look into the error. Perhaps it's a Byond version related issue?

2023-02-08 04:28 UTC, Zattarra commented
I am unable to reproduce the bug, I would like to know what version of Byond you are running. It's the only thing I can think of.

2023-02-10 21:54 UTC, BongaTheProto requested changes
Well it seems that recently a system to properly handle loadout accessories has been added, so I'd recommend looking into that to fit the croptops better

2023-02-11 21:55 UTC, BongaTheProto commented
fix the conflicts pls

2023-02-14 01:11 UTC, BongaTheProto commented on modular_splurt/code/modules/vending/clothesmate.dm
> +		/obj/item/clothing/accessory/formalcrop = 3
```suggestion
		/obj/item/clothing/accessory/formalcrop = 3,
```

2023-02-16 03:40 UTC, BongaTheProto approved these changes

2023-02-16 03:41 UTC, merged