Arousal meter in the UI
SPLURT-Station/S.P.L.U.R.T-Station-13 pull request #732
Opened 2023-02-02 18:54 UTC by admiralLusitano

Adds an arousal meter to the game's interface. The heart gets filled allong with the mob's lust and goes grey when climax'd.

Co-Authored-By: Comicao1 <33708588+comicao1@users.noreply.github.com>

# About The Pull Request
This PR adds a icon to the mob's screen that displays their lust level through a heart.

## Why It's Good For The Game
The game doesn't display the player's lust as far as I know, so that would be a good visual change.

## A Port?
The icon is from Citadel, but most of the code was rewritten to work with SPLURT.

## Pre-Merge Checklist

- [ ] You tested this on a local server.
- [ ] This code did not runtime during testing.
- [ ] You documented all of your changes.

## Changelog

:cl:
add: Added an arousal meter to the game's interface
/:cl:

2023-02-03 00:02 UTC, BongaTheProto requested changes

2023-02-03 00:02 UTC, BongaTheProto commented on modular_splurt/code/modules/mob/living/carbon/human/life.dm
> +		update_arousal()
It'd be better to update the hud whenever the procs that edit the lust amount are called rather than with every tick to minimize lag

2023-02-03 00:02 UTC, BongaTheProto commented on modular_splurt/code/modules/arousal/arousal.dm
> +
Why not just using `update_arousal_hud()`?

2023-02-05 07:11 UTC, davidchan13 commented
Minor suggestion: make clicking the icon open the interact with menu.

Also outside scope but some means to determine someone elses arousal would be nice too

2023-02-22 22:21 UTC, closed without merging