Allows prison jumpsuits to be reskinned, complimenting alternative titles for prisoners
SPLURT-Station/S.P.L.U.R.T-Station-13 pull request #782
Opened 2023-03-04 14:37 UTC by NopemanMcHalt

# About The Pull Request
Adds color-coded prison jumpsuit as reskins. Idea is borrowed from Prison Architect (at least, before Paradox's acquirement).

## Why It's Good For The Game
So officers can enforce and change jumpsuit depending on prisoner behavior or their charges.

## A Port?
Ported from ye olde [Skyrat13](https://github.com/Skyrat-SS13/Skyrat13).

## Pre-Merge Checklist

- [ ] You tested this on a local server.
- [ ] This code did not runtime during testing.
- [ ] You documented all of your changes.

## Changelog

:cl: Anonymous
add: Prison jumpsuits can be re-skinned into other color-coded security level, including protective custody.
/:cl:

2023-03-06 06:19 UTC, NopemanMcHalt commented on modular_splurt/code/modules/clothing/under/miscellaneous.dm
> +		"prot-sec"			= list("icon_state" = "protprisoner_skirt")
That's sadism but I'll try it.

2023-03-06 06:38 UTC, NopemanMcHalt commented on modular_splurt/code/modules/clothing/under/miscellaneous.dm
> +		"prot-sec"			= list("icon_state" = "protprisoner_skirt")
Nevermind it worked. Reskin button is kept to be CTRL.

2023-03-07 03:26 UTC, BongaTheProto requested changes

2023-03-07 03:26 UTC, BongaTheProto commented on modular_splurt/code/modules/clothing/under/miscellaneous.dm
> +		"med-sec"			= list("icon_state" = "prisoner"),
```suggestion
		"med-sec"			= list("icon_state" = "prisoner", "icon" = 'icons/obj/clothing/uniforms.dmi', "mob_overlay_icon" = null, "anthro_mob_worn_overlay" = null),
```

2023-03-07 03:26 UTC, BongaTheProto commented on modular_splurt/code/modules/clothing/under/miscellaneous.dm
> +		"med-sec"			= list("icon_state" = "prisoner_skirt"),
```suggestion
		"med-sec"			= list("icon_state" = "prisoner_skirt",  "icon" = 'icons/obj/clothing/uniforms.dmi', "mob_overlay_icon" = null, "anthro_mob_worn_overlay" = null),
```

2023-03-10 03:30 UTC, merged