Text fixes for cryoing and joining as Blueshield and Bridge Officer, removed mafia from ghosts, minor grenade fix
SPLURT-Station/S.P.L.U.R.T-Station-13 pull request #791
Opened 2023-03-22 22:42 UTC by KeplerWasTaken

# About The Pull Request

This PR changes the messages heads of staff and AI get when cryoing, the greeting messages for the Blueshield and BO, removes the mafia option from ghosts, and fixes an issue related to custom grenades and timers.

## Why It's Good For The Game

Changes were made on behalf of the staff team to have more up to date in-game texts.

## A Port?

nyo

## Pre-Merge Checklist

- [ ] You tested this on a local server.
- [ ] This code did not runtime during testing.
- [ ] You documented all of your changes.

## Changelog

:cl:
del: Mafia option for ghosts
tweak: Greeting message for Blueshield & Bridge Officer
tweak: Cryo message for Heads of Staff & AI
fix: Using a screwdriver on an unfinished grenade no longer changes its timer
/:cl:

2023-03-23 08:05 UTC, BongaTheProto requested changes

2023-03-23 08:05 UTC, BongaTheProto commented on config/entries/alert.txt
> +ALERT_RED_DOWNTO The station's destruction has been averted. There is still however an immediate serious threat to the station.
Since these are config changes they'd probably be better made directly on the local config

2023-03-27 21:12 UTC, KeplerWasTaken commented on code/game/objects/items/grenades/chem_grenade.dm
> +		..(user, I, null)
The fix has been taken out instead as it wasn't correct

2023-03-27 21:20 UTC, KeplerWasTaken commented
Will be closing this and opening a new PR so I can keep it clean :3

2023-03-28 21:27 UTC, closed without merging