Vacuum Resistance quirk.
SPLURT-Station/S.P.L.U.R.T-Station-13 pull request #946
Opened 2023-09-01 23:00 UTC by ariaworld

# About The Pull Request
Adds a new Quirk: Vacuum Resistance.

## Why It's Good For The Game

This quirk is beneficial for the game because it opens up new gameplay opportunities in keeping with the server's non-pvp, roleplay focus. Many players previously enjoyed spacewalking as zombies, indicating interest in vacuum traversal. As a modular quirk, this quirk allows any character to optionally gain this opportunity. This promotes creativity in backstories and uniqueness in personas. Since space survival is no longer limited to certain species, characters have more freedom to explore space, enhancing that gameplay aspect. Roleplaying and interacting in space settings also becomes more viable. Overall, modularizing vacuum adaptation into an equitable quirk allows more players to experience enjoyable space gameplay and enables creative roleplay potential.

## A Port?

Nope!

## Pre-Merge Checklist

- [ ] You tested this on a local server.
- [ ] This code did not runtime during testing.
- [ ] You documented all of your changes.

## Changelog

:cl:
add: Vacuum Resistance (Quirk)
/:cl:

2023-09-02 00:40 UTC, BongaTheProto requested changes

2023-09-02 00:40 UTC, BongaTheProto commented on modular_splurt/code/datums/traits/good.dm
> +		REMOVE_TRAIT(H, perks[A], ROUNDSTART_TRAIT)
```suggestion
	for(var/perk in perks)
		ADD_TRAIT(H, perk, ROUNDSTART_TRAIT)

/datum/quirk/vacuum_resistance/remove()
	. = ..()
	var/mob/living/carbon/human/H = quirk_holder
	for(var/perk in perks)
		REMOVE_TRAIT(H, perk, ROUNDSTART_TRAIT)
```

2023-09-09 08:17 UTC, remuluson2 commented
:D

2023-09-12 07:35 UTC, ariaworld commented on modular_splurt/code/datums/traits/good.dm
> +    var/list/perks = list(TRAIT_RESISTCOLD, TRAIT_RESISTLOWPRESSURE)
Thank youuuu <3
You're right, I should most likely add some sort of quirk to let other species not require oxygen!

2023-09-16 19:36 UTC, closed without merging